newcity/urls.py
# from django.conf.urls import patterns, include, url
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import TemplateView

from .views import (
    home,
    user_profile_detail,
    create_user_profile,
    my_profile_detail,
    my_matches,
    test_template,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home),
    url(r'^posts/', include("posts.urls", namespace="posts")),
    url(r'^users/(?P<user_profile_id>\d+)$', user_profile_detail, name= "user_profile_detail"),
    url(r'^users/create_user_profile/', create_user_profile, name= "create_user_profile"),
    url(r'^profile', my_profile_detail, name="my_profile_detail"),
    url(r'^matches', my_matches, name="my_matches" ),
    url(r'^test/',test_template),
    url(r'^login', TemplateView.as_view(template_name="login.html")),
    url(r'^logout', TemplateView.as_view(template_name="logout.html")),
    url(r'^accounts/', include('allauth.urls')),
]

posts/urls.py
# from django.conf.urls import include, url
# from django.contrib import admin

from django.conf.urls import url

from .views import (
  post_create_house,
  post_create_post,
  post_detail,
  post_list,
  post_update,
  post_delete,
  login,
  create_user,
  post_list_roommate,
)



urlpatterns = [
    url(r'^create_user/$', create_user),
    url(r'^list/(?P<initial_city>\D+)$', post_list, name='list'),
    url(r'^list_roommate/(?P<initial_city>\D+)$', post_list_roommate, name='list_roommate'),
    ##remove name in list and list_roommate
    url(r'^list/$', post_list, name='list'),
    url(r'^list_roommate/$', post_list_roommate, name='list_roommate'),
    url(r'^create_house/$', post_create_house, name='create_house'),
    url(r'^create_post/(?P<house_id>\d+)$', post_create_post, name='create_post'),
    url(r'^(?P<post_id>\d+)/$', post_detail, name="detail"),
    url(r'^update/$', post_update),
    url(r'^delete/$', post_delete),
]

posts/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=64, error_messages={'required': 'Please specify the city!', })
    created_timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return u'%s' % (self.name)

class Address(models.Model):
    street = models.CharField(max_length=128, error_messages={'required': 'Please specify the street name!', })
    city = models.ForeignKey(City)
    created_timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return u'%s, %s' % (self.street, self.city)

    def __str__(self):
        return u'%s, %s' % (self.street, self.city)


# TODO: adding users via admin hangs
class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER = (
        (MALE, 'Male'),
        (FEMALE, 'Female')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,)
    city_to = models.ForeignKey(City, null=True, blank=True, related_name = 'city_to')
    gender = models.CharField(max_length=1, choices=GENDER, null=False)
    school = models.CharField(max_length=50)
    hometown = models.ForeignKey(City, null=True, blank=True, related_name = "hometown")
    budget = models.PositiveIntegerField(default=0) #Max amount user can afford
    job = models.CharField(max_length=50)
    age = models.PositiveIntegerField(default=0)
    birthday = models.DateField(error_messages={'invalid': "Please enter a correct date format"}, null=True, blank=True)
    picture = models.CharField(max_length=100, blank=True, null=True)
    friends = models.ManyToManyField('self', through='Friendship',
                                     symmetrical=False)
    tags = models.ManyToManyField('Tag', through='UserProfileTag', blank=True)

    RELATIONSHIP = (
        ('S', 'Single'),
        ('E', 'Engaged'),
        ('M', 'Married'),
        ('I', 'In a relationship'),
    )

    relationship_status = models.CharField(max_length=50, choices=RELATIONSHIP, null=False)
    created_timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True, blank=True)
    last_active = models.DateTimeField(auto_now_add=False, auto_now=False, null=True, blank=True)

    def get_tags(self):
        return ",".join([str(tag) for tag in self.tags.all()])

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username


class Subletter(models.Model):
    profile = models.OneToOneField(UserProfile)


class Tenant(models.Model):
    profile = models.OneToOneField(UserProfile)


class House(models.Model):
    title = models.CharField(max_length=100, default="")
    content = models.TextField(max_length=1000, default="")
    #How shoulld users input address
    address = models.OneToOneField(Address, default="", null=True, blank=True)
    photos = models.ManyToManyField('self', through='HouseImage',
                                     symmetrical=False)
    price = models.PositiveIntegerField(default=0)
    beds = models.PositiveIntegerField(default=0)
    baths = models.PositiveIntegerField(default=0)
    pet_allowed = models.BooleanField(default=False)
    has_pool = models.BooleanField(default=False)
    has_parking = models.BooleanField(default=False)
    has_laundry = models.BooleanField(default=False)
    created_timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class Friendship(models.Model):
    user_source = models.ForeignKey(UserProfile, related_name='user_source')
    user_target = models.ForeignKey(UserProfile, related_name='user_target')
    created_timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

class Post(models.Model):
    user = models.ForeignKey(UserProfile, related_name='post_user_profile', blank=True, null=True)
    title = models.CharField(max_length=100, default="")
    house = models.OneToOneField(House, null=True, blank=True)
    #Tag is in quotations because of order of code
    # tags = models.ManyToManyField('Tag', through='PostTag', blank=True)
    created_timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self):
        return str(self.id)

    def __str__(self):
        return str(self.id)

    def get_user(self):
        return self.user

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"post_id": self.id})
        # return "posts/%s" %(self.id)

class Tag(models.Model):
    name = models.CharField(max_length=50)
    content = models.CharField(max_length=100)
    posts = models.ManyToManyField(UserProfile, through='UserProfileTag', blank=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class UserProfileTag(models.Model):
    user_profile = models.ForeignKey(UserProfile)
    tag = models.ForeignKey(Tag)


class HouseImage(models.Model):
    house = models.ForeignKey(House)
    image = models.ForeignKey('Image')

class Image(models.Model):
    image = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
	{% if user.is_authenticated %}
	<li><a href="{% url 'account_email' %}">Change E-mail</a></li>
	<li><a href="{% url 'account_logout' %}">Sign Out</a></li>
	{% else %}
	<li><a href="{% url 'account_login' %}">Sign In</a></li>
	<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
	{% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

templates/create_post.html
<!--DOCTYPE html -->
<html>
<head>
  <title>{% block head_title %}Post Create{% endblock head_title %}</title>
</head>
<body>
<div class='container'>
<h1> Form </h1>
<form method='POST' action="">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create Post"/>
</form>
</div>
</body>
</html>

templates/edit_profile.html
<!--DOCTYPE html -->
<html>
<head>
  <title>{% block head_title %}Edit Profile{% endblock head_title %}</title>
</head>
<body>
<div class='container'>
<h1> Form </h1>
<form method='POST' action="">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Change Profile"/>
</form>
</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <title></title>
</head>
<body>
    


    {% if user.is_authenticated %}
        Welcome back {{ user.username }}
    {% else %}
        You are not logged in
    {% endif %}
    <h1>This is Post List</h1>
</body>
</html>

templates/login.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Apt 5A | Facebook Login</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Plugins -->
  <link href="{% static 'assets/css/simpletextrotator.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/et-line-font.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/magnific-popup.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/flexslider.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">

  <!-- Template core CSS -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- Custom css -->
  <link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
</head>
<body>

  <!-- PRELOADER -->
  <div class="page-loader">
    <div class="loader">Loading...</div>
  </div>
  <!-- /PRELOADER -->

  <!-- NAVIGATION -->
  <nav class="navbar navbar-custom navbar-transparent navbar-fixed-top" role="navigation">

      <div class="container">

        <div class="navbar-header">
          <a class="navbar-brand" href="/">Apt 5A</a>
        </div>

        <div class="collapse navbar-collapse" id="custom-collapse">

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="/logout">Logout</a></li>
            <li><a href="/matches">My Matches</a>
            <li><a href="/profile">My Profile</a>
            {% endif %}
          </ul>
        </div>

      </div>

  </nav>

  <section id="home" class="module-hero module-parallax module-fade module-full-height bg-dark-30" data-background="assets/images/indoorApt1.jpg">

    <div class="hs-caption container">
      <div class="caption-content">
        <div class="hs-title-size-1 font-inc">
            <div class="facebook">
              <div>{% include "socialaccount/snippets/provider_list.html" with process="login" %}<div><br><br>
              <!-- goes to questionnaire -->
            </div>
            <form action="#" class="loginForm"> <!--reciever of information-->
                <input type="text" name="email" placeholder="Email or Username"><br><br>
                <input type="text" name="email" placeholder="Password"><br><br>
                <input type="submit" value="Submit">
            </form>
        </div><br><br>
        <div class="hs-title-size-1 font-inc">
        Don't have an account?<br>
          <a href="signup.html">--Sign Up--</a>
        </div>

      </div>
    </div>
  </section >

  <div class="wrapper">

  <!-- FOOTER -->
    <footer class="footer">

      <div class="container">

        <div class="row">

          <div class="col-sm-12 text-center">
            <p class="copyright font-inc m-b-0">© 2016 <a href="index.html">APT 5A</a>, All Rights Reserved.</p>
          </div>

        </div>

      </div>

    </footer>
    <!-- /FOOTER -->

  </div>
  <!-- /WRAPPER -->

  <!-- Scroll-up -->
  <div class="scroll-up">
    <a href="#totop"><i class="fa fa-angle-double-up"></i></a>
  </div>

  <!-- Javascript files -->
  <script src="{% static 'assets/js/jquery-2.1.3.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.mb.YTPlayer.min.js' %}"></script>
  <script src="{% static 'assets/js/appear.js' %}"></script>
  <script src="{% static 'assets/js/jquery.simple-text-rotator.min.js' %}"></script>
  <script src="{% static 'assets/js/jqBootstrapValidation.js' %}"></script>
  <script src="http://maps.google.com/maps/api/js?sensor=true' %}"></script>
  <script src="{% static 'assets/js/gmaps.js' %}"></script>
  <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/js/imagesloaded.pkgd.js' %}"></script>
  <script src="{% static 'assets/js/jquery.flexslider-min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.fitvids.js' %}"></script>
  <script src="{% static 'assets/js/smoothscroll.js' %}"></script>
  <script src="{% static 'assets/js/wow.min.js' %}"></script>
  <script src="{% static 'assets/js/contact.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>

</body>
</html>

templates/post_detail.html
<!--DOCTYPE html -->
<html>
<head>
  <title>{% block head_title %}Apt 5A | Post Detail{% endblock head_title %}</title>
</head>

<body>
  <h1>{{ instance.title }}</h1>

  {{ instance.title }}</br>
  {{ instance.user.user }}</br>
  {{ instance.user.gender }}</br>
  {{ instance.user.address }}</br>
  {{ instance.user.birthday }}</br>
  {{ instance.user.friends }}</br>
  {{ instance.user.picture }}</br>
  {{ instance.user.create_timestamp }}</br>
  {{ instance.user.last_updated }}</br>
  {{ instance.user.last_active }}</br>
  </br>
</body>

</html>

templates/post_list2.html
<!--DOCTYPE html -->
<html>
<head>
  <title>{% block head_title %}Post List{% endblock head_title %}</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</head>

<body>
  <div>
    {% if initial_city %}
    <h1>Rooms Available in {{ initial_city }}</h1>
    {% else %}
    <h1>Rooms Available</h1>
    {% endif %}
  </div>

  <div class="output">

  <div>
  {% for post in post_list %}
  Title: {{ post.title }}</br>
  Name: {{ post.user.username }}
  Content: {{ post.house.content }} </br>
  Street: {{ post.house.address.street }} </br>
  City: {{ post.house.address.city.name }} </br>
  Price: {{ post.house.price }} </br>
  Relationship Status: {{ post.user.get_relationship_status_display}}</br>
  Gender: {{ post.user.gender }}</br>
  School: {{ post.user.school }}</br>
  Hometown: {{ post.user.hometown }} </br>
  Job: {{ post.user.job }} </br>
  Age: {{ post.user.age }} </br>
  Tags:
  {% for tag in post.user.tags.all %}
   {{tag.name}},
  {% endfor %}
  </br></br>
   {% endfor %}
  </div>
 </div>

  <p>
    <label for="amount">Monthly rent:</label>
    <input type="text" id="amount-rent" readonly>
  </p>
  <div id="rent-range"></div>

    <p>
      <label for="amount">Age range:</label>
      <input type="text" id="text-age" readonly>
    </p>
  <div id="age-range"></div>

  <form method='GET' action="" id="filter-school-form">{% csrf_token %}
    School: <input type="text" id="text-school">
    <input id = "input-school" type="submit" value="Search School"><br>
  </form>

<div id="div-gender">
  <input type="checkbox" class = "gender-class" name="filter-gender" value="M" /> Male <br>
  <input type="checkbox" class = "gender-class" name="filter-gender" value="F" /> Female
</div>

  <div id="div-relationship">
    <input type="checkbox" class="filter-relationship" value="S"> Single<br>
    <input type="checkbox" class="filter-relationship" value="E"> Engaged<br>
    <input type="checkbox" class="filter-relationship" value="M"> Married<br>
    <input type="checkbox" class="filter-relationship" value="I"> In a relationship<br>
  </div>

  <div id="div-tag">
    {% for tag in tag_list %}
    <input type="checkbox" class="filter-tag" value="{{ tag.name }}"> {{ tag.name }}
    {% endfor %}
  </div>

  {# facebook wrote a separate php script to run their searches #}
<!--   <script type="text/javascript">
    function func(){
      return false;
    }
  </script>
  <form action="" method="get" id="filter-search" onSubmit="return func()">
    <input id="search" name="search" type="text" value="Find filters"/>
    <input id="search-submit-buttom" name="search-button" type="button" value="Search" onClick="func()"/>
  </form> -->

  <form method='GET' action="" id="reset-form">{% csrf_token %}
        <input id = "reset" type="submit" value="Reset">
  </form>

  <a href='{% url 'posts:login' %}'>Build your profile</a>

  <script>
  $(function() {
    $("#rent-range").slider({
      range: true,
      min: 0,
      max: 5000,
      step: 100,
      values: [ 0, 5000 ],
      slide: function( event, ui )  {
        $("#amount-rent").val("$" + ui.values[0] + " - $" + ui.values[1]);
      },
      stop: function(event, ui) {
        console.log("slider stop");
        console.log($("#rent-range"))
        var values = $( "#rent-range" ).slider( "option", "values" )
        filter_post()
      }
    });
    $("#amount-rent").val("$" + $("#rent-range").slider("values", 0) + " - $" + $("#rent-range").slider("values", 1));
  });

  $(function() {
    $("#age-range").slider({
      range: true,
      min: 0,
      max: 100,
      step: 1,
      values: [ 0, 100 ],
      slide: function( event, ui )  {
        $("#text-age").val(ui.values[0] + " - " + ui.values[1]);
      },
      stop: function(event, ui) {
        filter_post()
      }
    });
    $("#text-age").val($("#age-range").slider("values", 0) + " - " + $("#age-range").slider("values", 1));
  });

  $(".gender-class").click(function(event){
        console.log("form submitted!")  // sanity check
        filter_post();
    });

  $(".filter-relationship").click(function(event){
        console.log("form submitted!")  // sanity check
        filter_post();
    });

  $(".filter-tag").click(function(event){
        console.log("form submitted!")  // sanity check
        filter_post();
    });

  $("#input-school").click(function(event){
        console.log("form submitted!")  // sanity check
        event.preventDefault();
        filter_post();
    });

  $("#reset-form").on('submit', function(event){
        // event.preventDefault();
        location.reload()
    });

  function filter_post() {
    console.log("filter_roommate is working!") // sanity check
    var rent = $( "#rent-range" ).slider( "option", "values" )
    var age = $("#age-range").slider("option", "values")
    var gender_selected = [];
    var relationship_selected = [];
    var filter_selected = [];
    $('#div-gender input:checked').each(function() {
      gender_selected.push($(this).val());
    });

    $('#div-relationship input:checked').each(function() {
      relationship_selected.push($(this).val());
    });

    $('#div-tag input:checked').each(function() {
      filter_selected.push($(this).val());
    });
    $.ajax({
        url : window.location.pathname,
        //"/posts/list_roommate/San%20Francisco"
        type : "GET", // http method
        data : { gender : gender_selected,
                 school: $("#text-school").val(),
                 price_low : rent[0],
                 price_high: rent[1],
                 age_low: age[0],
                 age_high: age[1],
                 relationship_status: relationship_selected,
                 filter_selected: filter_selected,
                }, // data sent with the post request

        // handle a successful response
        success : function(json) {
            console.log(json); // log the returned json to the console
            console.log("success"); // another sanity check
            var raw_html = document.createElement('html')
            raw_html.innerHTML = json
            var output = raw_html.getElementsByClassName("output")[0]
            $(".output").html(output)
            },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>");
                // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
        });
    };
</script>

</body>

</html>

templates/questionnaire.html
<!-- <!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
    <p>Step {{ wizard.steps.step1 }} of {{wizard.steps.count }}</p> -->

    <!-- validates form -->
<!--     {% for field in form %}
        {{field.error}}
    {% endfor %}

    <form action="/posts/questionnaire/" method="POST">{% csrf_token %}
    {{ wizard.management_form}}
    {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
            {{ form }}
        {% endfor %}
    {% else %}
        {{ wizard.form }}
    {% endif %}

    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}"> "first step" </button>
    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}"> "prev step" </button>

    <input type="submit" value="Submit" />

    </form>

    </body>
</html> -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  
  <title>Semantic - Minimal portfolio template</title>
  
  <!-- Bootstrap core CSS -->
  <link href="assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  
  <!-- Plugins -->
  <link href="assets/css/simpletextrotator.css" rel="stylesheet">
  <link href="assets/css/font-awesome.min.css" rel="stylesheet">
  <link href="assets/css/et-line-font.css" rel="stylesheet">
  <link href="assets/css/magnific-popup.css" rel="stylesheet">
  <link href="assets/css/flexslider.css" rel="stylesheet">
  <link href="assets/css/animate.css" rel="stylesheet">
  
  <!-- Template core CSS -->
  <link href="assets/css/style.css" rel="stylesheet">
  
  <!-- Custom css -->
  <link href="assets/css/custom.css" rel="stylesheet">
</head>
<body>

  <!-- PRELOADER -->
  <div class="page-loader">
    <div class="loader">Loading...</div>
  </div>
  <!-- /PRELOADER -->

  <!-- NAVIGATION -->
  <nav class="navbar navbar-custom navbar-transparent navbar-fixed-top" role="navigation">

      <div class="container">
    
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Apt 5A</a>
        </div>
    
        <div class="collapse navbar-collapse" id="custom-collapse">
    
          <ul class="nav navbar-nav navbar-right">
    
            <li><a href="login.html">Login</a></li>
    
            <li><a href="contact.html">Contact</a></li>
    
          </ul>
        </div>

      </div>

  </nav>
 <section id="home" class="module-hero module-parallax module-fade module-full-height bg-dark-30" data-background="assets/images/indoorApt1.jpg">

    <div class="hs-caption container">
      <div class="caption-content">
        <div class="hs-title-size-4 font-alt m-b-30">
          Questionnaire
        </div>
        <div class="hs-title-size-1 font-inc">
            <form action="#" class="loginForm"> <!--reciever of information-->
                <input type="text" name="school" placeholder="School"><br><br>
                <input type="text" name="hometown" placeholder="Hometown"><br><br>
                <input type="text" name="job" placeholder="Occupation"><br><br>
                <input type="submit" value="Submit">
            </form>
        </div><br><br>
      </div>
    </div>
  </section >

  <div class="wrapper">

  <!-- FOOTER -->
    <footer class="footer">
    
      <div class="container">
    
        <div class="row">
    
          <div class="col-sm-12 text-center">
            <p class="copyright font-inc m-b-0">© 2016 <a href="index.html">APT 5A</a>, All Rights Reserved.</p>
          </div>
    
        </div>
    
      </div>
    
    </footer>
    <!-- /FOOTER -->

  </div>
  <!-- /WRAPPER -->

  <!-- Scroll-up -->
  <div class="scroll-up">
    <a href="#totop"><i class="fa fa-angle-double-up"></i></a>
  </div>
  
  <!-- Javascript files -->
  <script src="assets/js/jquery-2.1.3.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/js/jquery.mb.YTPlayer.min.js"></script>
  <script src="assets/js/appear.js"></script>
  <script src="assets/js/jquery.simple-text-rotator.min.js"></script>
  <script src="assets/js/jqBootstrapValidation.js"></script>
  <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <script src="assets/js/gmaps.js"></script>
  <script src="assets/js/isotope.pkgd.min.js"></script>
  <script src="assets/js/imagesloaded.pkgd.js"></script>
  <script src="assets/js/jquery.flexslider-min.js"></script>
  <script src="assets/js/jquery.magnific-popup.min.js"></script>
  <script src="assets/js/jquery.fitvids.js"></script>
  <script src="assets/js/smoothscroll.js"></script>
  <script src="assets/js/wow.min.js"></script>
  <script src="assets/js/contact.js"></script>
  <script src="assets/js/custom.js"></script>

</body>
</html>

templates/tmp.html
<script type="text/javascript">
	function goSearch(){
		if ($('#s').val())
			window.location = "/search/"+escape($('#s').val());

		return false
	}
</script>

<div id="header-3">
	<div class="search-box rounded-corners">
		<form action="" class="search rounded-corners" id="site-search" method="get" onSubmit="return goSearch();">
			<div class="input-div">
				<input id="s" name="s" type="text" value="Search..." onfocus="this.value=''" />
			</div>
			<div class="submit-button">
				<input class="submit-button" id="site-search-submit" name="commit" type="button" value="Search" onClick="goSearch()" />
			</div>
		</form>
	</div>
</div>

templates/upload_image.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}Upload House Image{% endblock head_title %}</title>
  </head>

  <body>
    <div class='container'>
      <h1>Upload House Image</h1>
      <form method='POST' action="{% url 'posts:upload_house_image' %}" enctype="multipart/form-data">{% csrf_token %}
						<p>{{ form.non_field_errors }}</p>
            <p>{{ form.image.label_tag }} {{ form.image.help_text }}</p>
            <p>
                {{ form.image.errors }}
                {{ form.image }}
            </p>
            <p><input type="submit" value="Upload" /></p>
      </form>
    </div>
  </body>
</html>